//  Students
export const SET_ALL_STUDENTS = "STUDENTS:SET_ALL_STUDENTS";
export const UPDATE_STUDENT = "STUDENTS:UPDATE_STUDENT";
export const REMOVE_STUDENT = "STUDENTS:REMOVE_STUDENT";
export const ADD_STUDENT = "STUDENTS:ADD_STUDENT";

//  Lectures
export const SET_ALL_LECTURES = "LECTURES:SET_ALL_LECTURES";
export const UPDATE_LECTURE = "LECTURES:UPDATE_LECTURE";
export const REMOVE_LECTURE = "LECTURES:REMOVE_LECTURE";
export const ADD_LECTURE = "LECTURES:ADD_LECTURE";

//  Schedules
export const SET_ALL_SCHEDULES = "SCHEDULE:SET_ALL_SCHEDULES";
export const REMOVE_SCHEDULE = "SCHEDULE:REMOVE_SCHEDULE";
export const ADD_SCHEDULE = "SCHEDULE:ADD_SCHEDULE";

// Visits
export const SET_ALL_VISITS = "VISITS:SET_ALL_VISITS";
export const SET_NEW_VISITS = "VISITS:SET_NEW_VISITS";

